### ISSUE TITLE
Angel's Feedback on Technical Issues

### ISSUE THREAD

**Issue by Angelqijiadeng** [asibole1/Project#2]
Hi Alicia, your coding is very clear. I have the following suggestions after I run W3C Validator.

1. In your general.css line 66, top is not a align-items value. Please update it.
2. In your index.html line 75, there is a extra <tr>. It is just a minor mistake. I put my correction below.
<tr>
        <td><a href="recipes.html">Breakfast</a></td>
        <td><a href="recipes.html">Lunch</a></td>
</tr>
<tr>
      <td><img src="images/friedchicken.png" alt="dinner image"></td>
      <td><img src="images/minicheesecakes.png" alt="dessert image"></td>
</tr>

**Comment by asibole1** [comment]
Hi, Angel! Thank you very much. I have fixed both of these, thanks for catching them :)
