### ISSUE TITLE
Dylan Haddad's peer review

### ISSUE THREAD

**Issue by narluku** [asibole1/Project#3]
Hey Alicia! Really loved your website. As someone who doesn't cook that much, your recipes look really good and easy to make, which is great. 

Content suggestions: 

1- Adding a section where you add links to youtube channels or recommended cookbooks would be a great way to make your website visitors more stuck in the cooking world. 

2- Adding vegan or vegetarian meals would also be a great idea to attract a wider audience and make the website more inclusive. 

Technical issues:

1-  line 66, you can just remove it as you don't need the align-items top. In.css

2-  In reference.html you should add a title to your images.

**Comment by asibole1** [comment]
Hi Dylan, thanks so much! 
Content: 
1. Great idea! I added this to the reference section. 
2. I love that and would definitely do that in future recipes I add! Not adding more recipes in this final version, though. 

Technical: 
1. Great point, this is fixed! You helped me realize a couple others were unnecessary, too, that I removed. 
2. this is a great addition, and I have added it!
